[project]
name = "fgraph2"
version = "0.1.0"
description = "A toolkit that parses a Fortran codebase to a layered, structured knowledge graph instance"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "packages/*",
    "fscoping",
]
