[project]
name = "fgraphutils"
version = "0.1.0"
description = "Common data structure and utilities within fgraph project"
readme = "README.md"
authors = [
    { name = "Wanli-Wylie", email = "zhang.wl.earth@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pydantic"
]

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
